services:
  web-app:
    build:
      context: . # путь к dockerfile`у
    ports:
      - "8000:8000"
    volumes:
      - ./service:/service

    command: > # команда при запуске контейнера
      sh -c "python manage.py runserver 0.0.0.0:8000"