# Generated by Django 4.1.13 on 2024-06-10 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_subscription_services_su_field_a_155836_idx'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='subscription',
            name='services_su_field_a_155836_idx',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='field_a',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='field_b',
        ),
    ]
